apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-deployment
spec:
  selector:
    matchLabels:
      app: employee
  replicas: 3
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
        - name: employee
          image: gcr.io/netent-employee/netent:v1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: employee
  labels:
    app: employee
spec:
  selector:
    app: employee
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  type: LoadBalancer